### ISSUE TITLE
Consider requiring PURL and digital repository

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/cocina-models#291]
In current mapping from Fedora, `description > purl` and `description > access > digitalRepository > value: "Stanford Digital Repository"` are always added to Cocina objects. However, in Cocina objects created by other systems, they may be omitted.

Currently, this is not problematic because all Cocina objects provided by Dor-Services-App go through mapping. However, in the future when saving to Postgres, Cocina objects will be saved as provided by other systems and thus will omit the PURL and digital repository values. Should these be required to guarantee consistency?

For example:
```
description: {
              title: [
                {
                  value: "This is my title"
                }
              ]
        -     purl: "https://purl.stanford.edu/gg777gg7777",
        -     access: {
        -       digitalRepository: [
        -         {
        -           value: "Stanford Digital Repository"
        -         }
        -       ]
        -     }
            },
```

**Comment by arcadiafalcone** [comment]
@justinlittman Generally I tend towards trying to make the metadata explicit so that it's less reliant on being interpreted by code, but I think in this case given the trade-offs it will be OK to presume that "Stanford Digital Repository" can be inferred from the presence of a purl. The repository can be inserted as needed at publication time rather than required as part of the record. The purl should be required.

**Comment by justinlittman** [comment]
@arcadiafalcone @andrewjbtw Is it OK that dark / unpublished objects have PURLs specified?

**Comment by arcadiafalcone** [comment]
@justinlittman It's fine by me.
