### ISSUE TITLE
Support snakecase

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/cocina-models#335]
instead of current camelcase.

Use of camelcase should be allowed, but emit a deprecation warning.

Set deprecation horizon to 1.0 or 2.0 or something

**Comment by mjgiarlo** [comment]
We decided not to move forward with camels-to-snakes translation because the translation, we learned, leaks out of cocina-models to at least DSC and DSA and possibly many other locations. And given that concern and the timing of our work to replace Fedora and persist Cocina JSON directly, we are ending this work.
