### ISSUE TITLE
Add coordinate validator for map data

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/cocina-models#663]
Similar to #662 but related to `map` data (scanned map images) instead.

We have lots of problems with scanned map data that has coordinates that are in invalid formats; see for example:
- bb847xp3575
- bq428sj1172
- by513wd0839

@justinlittman also [made a report](https://github.com/sul-dlss/purl/issues/708#issuecomment-1782904904) that shows the breadth of coordinate data formats in scanned maps. 

This causes problems when the maps are released, but fail to index, and there's no way to know that except that they don't show up in Earthworks.

**Comment by justinlittman** [comment]
@thatbudakguy Can you specify what the validation would be?

**Comment by ndushay** [comment]
discussion implied:  how the validators work, and what is wished for

**Comment by justinlittman** [comment]
If we created this validator, all existing invalid coordinates would need to be fixed. Does that seem feasible?

**Comment by kimdurante** [comment]
Since this issue affects scanned maps and not geospatial data, I have been talking with the Maps team about possible ways to batch update records with missing or invalidate coordinates. Many older maps do not contain coordinates, or use a different projection, so we could perhaps generate approximate valid coordinates using the place name.

**Comment by justinlittman** [comment]
In cocina, this would be in description > subject > type = "map coordinates"?

**Comment by kimdurante** [comment]
Yes

**Comment by justinlittman** [comment]
The IIIF NavPlace element is created by https://github.com/iiif-prezi/osullivan/blob/main/lib/iiif/v3/presentation/nav_place.rb.

Would the validator (1) validate that every map coordinates subject can be parsed by this code and within the valid range or (2) validate that if a map coordinates subject can be parsed by this code, it is within the valid range or (3) other?

**Comment by kimdurante** [comment]
I am not familiar with this code. But I would lean towards option 2, validate that if a map coordinates subject can be parsed by this code, it is within the valid range.

**Comment by lwrubel** [comment]
At what point are the invalid coordinates being created?

We initially create the map coordinates subject in the `generate-descriptive` step by taking the coordinates in the ISO19139.xml's `MD_Metadata/identificationInfo/MD_DataIdentification/extent/EX_Extent/geographicElement/EX_GeographicBoundingBox` element. There is logic in the workflow step to convert these decimal coordinates into degrees/minutes/seconds. The intent there is to create a human-readable subject in the PURL. 

Later, `https://github.com/iiif-prezi/osullivan/blob/main/lib/iiif/v3/presentation/nav_place.rb` creates a navPlace for EarthWorks. It first converts the degrees/minutes/seconds back to decimal, using `geo_coord`.

The ticket is requesting that we identify invalid coordinates when creating the cocina object by creating a cocina validator that would not allow the cocina to be created in generate-descriptive. Alternatively, since we're already doing steps to convert the coordinates, we could raise an error in the workflow step if they are determined to be invalid?

**Comment by kimdurante** [comment]
This issue has to do with scanned maps, not geospatial data, so there is no ISO involved. In many cases, coordinates for  scanned maps are either missing or invalid, such as this item:
[https://purl.stanford.edu/bb847xp3575](https://purl.stanford.edu/bb847xp3575)

I think most, if not all, of the coordinates for our geospatial data should be valid. Errors would be raised earlier on in accessioning if they were missing, malformed, or out of bounds.

**Comment by lwrubel** [comment]
Thanks for explaining that, now I understand that these don't go through the gisAssembly workflow and why we need validation someplace else.

**Comment by thatbudakguy** [comment]
Based on [slack discussion](https://stanfordlib.slack.com/archives/C06CH4SRU8K/p1709927076826579), we've decided to abandon a cocina validator for coordinates because:
- the concept of "validity" is not straightforward (DMS form vs. decimal degrees form vs. lat/long; multiple vs. single coordinates)
- systems other than earthworks (e.g. exhibits) use coordinate metadata, and they accept it in different formats
- asking accessioneers/catalogers to remediate bad coordinate metadata in bulk as part of accessioning might be a heavy lift, especially if the data is coming from MARC
