### ISSUE TITLE
remove .from_dynamic and .from_json methods

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/cocina-models#81]
1.  confirm they are not used by dependents
2.  rip 'em out

@jcoyne believes @justinlittman found a better way.

**Comment by mjgiarlo** [comment]
@jcoyne @justinlittman can one of y'all comment on what the better way is?

**Comment by mjgiarlo** [comment]
Adding to backlog 'til we get that extra info in this issue.

**Comment by justinlittman** [comment]
Most of the extra code has already been removed. Getting completely rid of .from_dynamic and .from_json are the last bits.

```
      def self.from_dynamic(dyn)
        RequestAdminPolicy.new(dyn)
      end

      def self.from_json(json)
        from_dynamic(JSON.parse(json))
      end
```
from RequestAdminPolicy as an example.

Instead of `RequestPolicy.from_dynamic(dyn)`, `RequestPolicy.new(dyn)`.

Instead of `RequestPolicy.from_json(json)`, `RequestPolicy.new(JSON.parse(json))`.

**Comment by ndushay** [comment]
cool!
